### PR TITLE
Added Lithuanian Language Support [hacktoberfest]

### PR DESCRIPTION
**Pull request by Trol**
Hi there, so I've created a new file in the "app/src/main/res/values-lt-LT/ which is the "Lithuanian" or "Lietuvių kalba" language. I'm not sure how to implement into the application, and haven't been able to find it.
I hope you enjoy my contribution!

Regards,
Trol.

### CODE REVIEW

**Comment by RyuzakiKK** [comment]
Awesome thank you very much!
@Trol1337 you just need to change the folder name from `values-lt-LT` to `values-lt-rLT` and then it is perfect.

**Comment by Trol** [comment]
Just fixed the folder name!

**Comment by Trol** [comment]
@RyuzakiKK mind adding the "hacktoberfest" label? would be very much appreciated. :ok_hand:

**Comment by RyuzakiKK** [comment]
Sure no problem. But you should have this PR already counted for the hacktoberfest even without the tag.

**Comment by Trol** [comment]
This is my first time entering so not sure. :man_shrugging:

**Comment by RyuzakiKK** [comment]
Don't worry. Just log in to https://hacktoberfest.digitalocean.com/ and click "check your progress".

**Pull request merged**
