### PR TITLE
Add Hungarian translation

### PR DESCRIPTION
**Pull request by zandraaperjesi**

### CODE REVIEW

**Comment by RyuzakiKK** [comment]
Thank you so much!

**Comment by zandraaperjesi** [comment]
While translating I might have found a typo in the original file. I think line 88 "It\'s high recommended" is supposed to be "It\'s high**ly** recommended"

**Comment by RyuzakiKK** [comment]
Oh good catch. Feel free to do a PR to fix it. Otherwise I’ll do a commit
for it.

**Comment by zandraaperjesi** [comment]
I will, thanks :)

**Pull request merged**
