### PR TITLE
German Translation added

### PR DESCRIPTION
**Pull request by ghost**
Added a german translation of string.xml

### CODE REVIEW

**Comment by ghost** [comment]
# hacktoberfest

**Comment by RyuzakiKK** [comment]
Thank you very much.
Please put your translated string.xml inside a new folder called `values-de-rDE` in `/app/src/main/res/`
You can see the others translations here: https://github.com/RyuzakiKK/NoteCrypt/tree/master/app/src/main/res

**Comment by ghost** [comment]
uhm, so should i close this one and open a ne wone or how?

**Comment by RyuzakiKK** [comment]
ah no, just add another commit to your forked repo and this PR will be automatically updated

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
ok, done that @RyuzakiKK

**Comment by RyuzakiKK** [comment]
Awesome!

**Pull request merged**
